ui: mocha-bdd
# tunnel_host: http://focusaurus.com
browsers:
  - name: chrome
    platform: Windows 10
    version:
      - 69
      - latest
  - name: firefox
    platform: Windows 10
    version:
      - 60
      - latest
  - name: safari
    version:
      - 11
      - latest
  - name: MicrosoftEdge
    version:
      - 17
      - latest
  # - name: iphone
  #   version: latest
  # Not Supported
  # - name: internet explorer
  #   version: 11
  #   platform: Windows 10
  # - name: internet explorer
  #   version: 9..latest
