ui: mocha-bdd
#server: ./test/support/server.js
tunnel_host: http://focusaurus.com
browsers:
  - name: chrome
    platform: Windows 10
    version:
      - 69
      - latest
  - name: firefox
    platform: Windows 10
    version:
      - 60
      - latest
  - name: safari
    version:
      - 11
      - latest
  - name: MicrosoftEdge
    version:
      - 17
      - 18
  # - name: ipad
  #   version:
  #     - 11.3
  #     - latest
  # - name: internet explorer
  #   version: 11
